### ISSUE TITLE
 * AdversarialDriving (not found in project, manifest or registry)

### ISSUE THREAD

**Issue by weilianzhen** [sisl/Registry#31]
Hello!
I meet this problem:

ERROR: The following package names could not be resolved:
 * AdversarialDriving (not found in project, manifest or registry)

thank you!

**Comment by rejuvyesh** [comment]
Could you clarify what were you trying to do when you got this error? https://github.com/sisl/AdversarialDriving.jl is not registered in this registry.

**Comment by weilianzhen** [comment]
> Could you clarify what were you trying to do when you got this error? https://github.com/sisl/AdversarialDriving.jl is not registered in this registry.

Sorry,maybe I put the question in the wrong place and I will give some details of my question.
I am a new learner of Julia and  I have downloaded the AdversarialDriving.jl .When I run this code in AdversarialDriving.jl/test:
julia runtests.jl 
I meet this problem:
ERROR: LoadError: LoadError: ArgumentError: Package AdversarialDriving not found in current path:
- Run `import Pkg; Pkg.add("AdversarialDriving")` to install the AdversarialDriving package.

Then ,I use:
(@v1.5) pkg> add AdversarialDriving

It tells me:
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Updating registry at `~/.julia/registries/JuliaPOMDP`
   Updating git-repo `https://github.com/JuliaPOMDP/Registry`
   Updating registry at `~/.julia/registries/SISL`
   Updating git-repo `https://github.com/sisl/Registry`
ERROR: The following package names could not be resolved:
 * AdversarialDriving (not found in project, manifest or registry)

Thank you again!

**Comment by MaximeBouton** [comment]
AdversarialDriving is not a registered package so you cannot add it using `Pkg.add`. 

The proper way to add this package is to directly use its url: 
```
import Pkg; Pkg.add(url="https://github.com/sisl/AdversarialDriving.jl")
``` 

In the future, issues would be better placed here https://github.com/sisl/AdversarialDriving.jl/issues

I opened one for your convenience: https://github.com/sisl/AdversarialDriving.jl/issues/7 

Thank you for reporting!

**Comment by ancorso** [comment]
Thanks for bringing this to our attention. I've added Maxime's installation instructions to the README.
